-- ─── Part A: equip_service_areas (17 áreas) ──────────────────────────
-- NOTA: "Adolecentes" (sin "s" intermedia) es un typo histórico del
-- vocabulario canónico de passion_groups — se preserva verbatim.
INSERT INTO public.equip_service_areas
  (slug, name, gift_profile, skill_profile, disc_profile,
   passion_groups, passion_types, experience_types, sort_order)
VALUES
  ('ensenanza', 'Enseñanza y Discipulado',
   '{"ensenanza":1.0,"pastoreo":0.5,"sabiduria":0.5,"conocimiento":0.5,"exhortacion":0.5,"profecia":0.5}'::jsonb,
   '{"I":0.8,"S":0.7,"C":0.5}'::jsonb,
   '{"D":0.5,"I":0.4,"S":0.5,"C":0.6}'::jsonb,
   ARRAY['Adultos solteros','Matrimonios jóvenes sin hijos','Matrimonios jóvenes con hijos','Nuevos cristianos'],
   ARRAY['Enseñando','Liderando','Influyendo'],
   ARRAY['spiritual','religious'],
   1),

  ('ninez', 'Niñez',
   '{"ensenanza":1.0,"pastoreo":0.8,"misericordia":0.5,"servicio":0.5}'::jsonb,
   '{"S":0.9,"A":0.5,"R":0.4}'::jsonb,
   '{"D":0.2,"I":0.8,"S":0.8,"C":0.3}'::jsonb,
   ARRAY['Bebés','Preescolares','Niños de edad escolar'],
   ARRAY['Enseñando','Sirviendo','Socializando'],
   ARRAY['spiritual'],
   2),

  ('juventud', 'Adolescentes y Juventud',
   '{"pastoreo":1.0,"ensenanza":0.8,"exhortacion":0.5,"liderazgo":0.5}'::jsonb,
   '{"S":0.9,"E":0.6,"A":0.5}'::jsonb,
   '{"D":0.5,"I":0.9,"S":0.5,"C":0.2}'::jsonb,
   ARRAY['Adolecentes','Jóvenes','Estudiantes universitarios','Hijos de pastores','Hijos de padres solteros'],
   ARRAY['Enseñando','Liderando','Socializando','Desafiando'],
   ARRAY['spiritual','victory','failure'],
   3),

  ('adoracion', 'Adoración y Música',
   '{"servicio":0.8,"liderazgo":0.6,"fe":0.5}'::jsonb,
   '{"A":1.0,"S":0.5,"E":0.4}'::jsonb,
   '{"D":0.4,"I":0.8,"S":0.4,"C":0.4}'::jsonb,
   ARRAY['Artistas: músicos, actores, escritores','Jóvenes','Adultos solteros'],
   ARRAY['Protagonizando','Creando','Influyendo'],
   ARRAY['spiritual'],
   4),

  ('multimedia', 'Producción Técnica y Multimedia',
   '{"servicio":1.0,"administracion":0.5,"conocimiento":0.5}'::jsonb,
   '{"R":0.7,"C":0.7,"A":0.5,"I":0.5}'::jsonb,
   '{"D":0.2,"I":0.2,"S":0.6,"C":0.9}'::jsonb,
   ARRAY['Jóvenes','Estudiantes universitarios'],
   ARRAY['Creando','Organizando','Administrando'],
   ARRAY[]::text[],
   5),

  ('diseno', 'Diseño y Comunicación',
   '{"servicio":0.6,"sabiduria":0.5,"ayuda":0.5}'::jsonb,
   '{"A":1.0,"C":0.6,"I":0.4}'::jsonb,
   '{"D":0.2,"I":0.5,"S":0.4,"C":0.8}'::jsonb,
   ARRAY['Artistas: músicos, actores, escritores'],
   ARRAY['Creando','Innovando','Perfeccionando'],
   ARRAY[]::text[],
   6),

  ('tecnologia', 'Tecnología y Desarrollo',
   '{"conocimiento":0.8,"sabiduria":0.6,"servicio":0.6}'::jsonb,
   '{"I":0.9,"C":0.8,"R":0.5}'::jsonb,
   '{"D":0.3,"I":0.3,"S":0.4,"C":0.9}'::jsonb,
   ARRAY['Estudiantes universitarios','Ejecutivos y profesionales'],
   ARRAY['Innovando','Mejorando','Organizando'],
   ARRAY[]::text[],
   7),

  ('hospitalidad', 'Hospitalidad y Bienvenida',
   '{"hospitalidad":1.0,"servicio":0.8,"misericordia":0.5}'::jsonb,
   '{"S":0.9,"E":0.4,"C":0.3}'::jsonb,
   '{"D":0.2,"I":0.9,"S":0.8,"C":0.2}'::jsonb,
   ARRAY['Nuevos cristianos','Nuevos miembros de la iglesia','No cristianos'],
   ARRAY['Socializando','Sirviendo','Defendiendo'],
   ARRAY['spiritual'],
   8),

  ('oracion', 'Intercesión y Oración',
   '{"fe":1.0,"discernimiento":0.8,"sabiduria":0.6,"misericordia":0.5}'::jsonb,
   '{"S":0.5,"C":0.5,"I":0.4}'::jsonb,
   '{"D":0.2,"I":0.2,"S":0.8,"C":0.7}'::jsonb,
   ARRAY['Enfermos terminales','Familiares de enfermos terminales','Cristianos desilusionados'],
   ARRAY['Sirviendo','Reparando','Defendiendo'],
   ARRAY['spiritual','painful'],
   9),

  ('cuidado', 'Cuidado Pastoral y Consolación',
   '{"misericordia":1.0,"pastoreo":0.6,"ayuda":0.6,"discernimiento":0.5,"servicio":0.5}'::jsonb,
   '{"S":0.9,"C":0.4,"R":0.4}'::jsonb,
   '{"D":0.1,"I":0.4,"S":0.9,"C":0.5}'::jsonb,
   ARRAY['Enfermos terminales','Familiares de enfermos terminales','Divorciados','Cristianos desilusionados','Hospitalizados'],
   ARRAY['Sirviendo','Reparando','Defendiendo'],
   ARRAY['painful','victory'],
   10),

  ('accion-social', 'Acción Social y Misericordia',
   '{"misericordia":1.0,"servicio":0.8,"ayuda":0.8,"dar":0.6,"fe":0.5}'::jsonb,
   '{"S":0.8,"R":0.6,"E":0.4}'::jsonb,
   '{"D":0.3,"I":0.4,"S":0.8,"C":0.4}'::jsonb,
   ARRAY['Indigentes','Gente en pobreza extrema','Desempleados','Abusados sexualmente','Hospitalizados'],
   ARRAY['Sirviendo','Reparando','Defendiendo'],
   ARRAY['painful','failure'],
   11),

  ('evangelismo', 'Evangelismo y Misiones',
   '{"evangelismo":1.0,"fe":0.8,"exhortacion":0.6,"liderazgo":0.5,"servicio":0.5}'::jsonb,
   '{"E":0.8,"S":0.7,"R":0.4}'::jsonb,
   '{"D":0.8,"I":0.8,"S":0.3,"C":0.2}'::jsonb,
   ARRAY['No cristianos','Cristianos nominales','Grupos indígenas','Extranjeros'],
   ARRAY['Desafiando','Influyendo','Sirviendo'],
   ARRAY['spiritual','victory'],
   12),

  ('administracion', 'Administración y Operaciones',
   '{"administracion":1.0,"servicio":0.6,"sabiduria":0.5,"conocimiento":0.5}'::jsonb,
   '{"C":1.0,"I":0.5,"E":0.4}'::jsonb,
   '{"D":0.3,"I":0.2,"S":0.6,"C":0.9}'::jsonb,
   ARRAY['Ministros','Esposas de ministros'],
   ARRAY['Administrando','Organizando','Perfeccionando'],
   ARRAY[]::text[],
   13),

  ('logistica', 'Logística y Servicio Práctico',
   '{"ayuda":1.0,"servicio":1.0,"administracion":0.5,"dar":0.5}'::jsonb,
   '{"R":0.9,"C":0.6,"S":0.4}'::jsonb,
   '{"D":0.2,"I":0.3,"S":0.9,"C":0.6}'::jsonb,
   ARRAY[]::text[],
   ARRAY['Organizando','Sirviendo','Perfeccionando'],
   ARRAY[]::text[],
   14),

  ('liderazgo', 'Liderazgo y Coordinación',
   '{"liderazgo":1.0,"administracion":0.7,"sabiduria":0.6,"discernimiento":0.5,"exhortacion":0.5}'::jsonb,
   '{"E":1.0,"S":0.5,"C":0.5}'::jsonb,
   '{"D":0.9,"I":0.6,"S":0.2,"C":0.4}'::jsonb,
   ARRAY['Ministros','Esposas de ministros','Nuevos miembros de la iglesia'],
   ARRAY['Liderando','Organizando','Desafiando','Mejorando'],
   ARRAY['victory','failure'],
   15),

  ('vida-congregacional', 'Vida Congregacional',
   '{"pastoreo":1.0,"hospitalidad":0.6,"ensenanza":0.6,"exhortacion":0.5,"misericordia":0.5}'::jsonb,
   '{"S":0.9,"E":0.5,"C":0.4}'::jsonb,
   '{"D":0.3,"I":0.7,"S":0.8,"C":0.3}'::jsonb,
   ARRAY['Amas de casa','Madres solteras','Mujeres solteras embarazadas','Madres casadas que trabajan','Madres de adolescentes','Mujeres que abortaron','Esposas de ministros','Padres de familia','Adultos de la tercera edad','Discapacitados','Parejas en su etapa de prometidos','Matrimonios jóvenes sin hijos','Matrimonios jóvenes con hijos','Matrimonios con hijos adolecentes','Matrimonios con hijos adultos','Creyentes casados con no creyentes'],
   ARRAY['Socializando','Sirviendo','Enseñando'],
   ARRAY['spiritual','victory'],
   16),

  ('restauracion', 'Restauración y Recuperación',
   '{"misericordia":1.0,"discernimiento":0.8,"exhortacion":0.7,"pastoreo":0.6,"fe":0.5}'::jsonb,
   '{"S":0.9,"I":0.4}'::jsonb,
   '{"D":0.2,"I":0.4,"S":0.9,"C":0.4}'::jsonb,
   ARRAY['Adictos al alcohol o a las drogas','Gente involucrada en la pornografía','Prisioneros','Ex convictos','Familiares de prisioneros','Personas que han escapado de su casa','Pacientes con SIDA','Homosexuales y lesbianas'],
   ARRAY['Reparando','Defendiendo','Sirviendo'],
   ARRAY['painful','failure','victory'],
   17);

-- ─── Part B: equip_ministries (22 ministerios) ───────────────────────
-- NOTA: las descripciones son un borrador (draft) redactado por Claude —
-- no existía copy pastoral en ninguna fuente. Pendiente revisión/edición
-- de Luis antes de mostrarse como definitivas.
-- NOTA: "Líderes de Estudio Bíblico" fue excluido a propósito (decisión
-- 2026-07-08) — no se siembra en este archivo.
INSERT INTO public.equip_ministries (name, description, service_area_ids, active)
VALUES
  ('Infantiles y de Familia',
   'Cuidado y enseñanza a niños en edad escolar y sus familias los domingos.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='ninez'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('Alabanza y Multimedia',
   'Equipo de música y producción técnica que acompaña los cultos.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='adoracion'),
         (SELECT id FROM public.equip_service_areas WHERE slug='multimedia')],
   true),

  ('Equipo de Bienvenida',
   'Recibe y orienta a visitantes y nuevos miembros en cada culto.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='hospitalidad')],
   true),

  ('Grupos de Oración',
   'Espacios de intercesión constante por la congregación y sus necesidades.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='oracion')],
   true),

  ('Misiones',
   'Alcance evangelístico y proyectos misioneros transculturales.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='evangelismo')],
   true),

  ('Apoyo Administrativo',
   'Soporte administrativo y de procesos para la operación de la iglesia.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='administracion')],
   true),

  ('Cuidado Pastoral',
   'Acompañamiento y consolación a personas en momentos difíciles.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='cuidado')],
   true),

  ('Directores de Culto',
   'Coordinan y dirigen el desarrollo de los cultos.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='adoracion'),
         (SELECT id FROM public.equip_service_areas WHERE slug='liderazgo')],
   true),

  ('Misericordia',
   'Ayuda práctica a personas en necesidad dentro y fuera de la congregación.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='accion-social')],
   true),

  ('Montaje',
   'Instalación y logística del espacio antes y después de las actividades.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='logistica')],
   true),

  ('Ornato',
   'Cuidado estético y ambientación de los espacios de la iglesia.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='diseno')],
   true),

  ('Coram Deo — Jóvenes',
   'Discipulado y comunidad para adolescentes y jóvenes.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='juventud'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('Coram Deo — Universitarios',
   'Discipulado y comunidad para estudiantes universitarios.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='juventud'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('Diseño y Comunicación',
   'Piezas gráficas y comunicación visual de la iglesia.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='diseno')],
   true),

  ('Desarrollo Tecnológico',
   'Soporte y desarrollo de herramientas tecnológicas de la iglesia.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='tecnologia')],
   true),

  ('Ministerio de Damas',
   'Comunidad, enseñanza y crecimiento para las mujeres de la iglesia.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='vida-congregacional'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('Ministerio de Caballeros',
   'Comunidad, enseñanza y crecimiento para los hombres de la iglesia.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='vida-congregacional'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('+ Unidos (células en casas)',
   'Grupos pequeños que se reúnen en casas para estudio y comunidad.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='ensenanza'),
         (SELECT id FROM public.equip_service_areas WHERE slug='hospitalidad')],
   true),

  ('Matrimonios Jóvenes',
   'Acompañamiento y enseñanza para matrimonios de menos de 10 años.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='vida-congregacional'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('Matrimonios',
   'Acompañamiento y enseñanza para matrimonios de más de 10 años.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='vida-congregacional'),
         (SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true),

  ('Impacto Social',
   'Ayuda a la comunidad cercana y viajes misioneros de corto plazo.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='accion-social'),
         (SELECT id FROM public.equip_service_areas WHERE slug='evangelismo')],
   true),

  ('3D (enseñanza doctrinal)',
   'Enseñanza doctrinal a profundidad para la congregación.',
   ARRAY[(SELECT id FROM public.equip_service_areas WHERE slug='ensenanza')],
   true);
